### ISSUE TITLE
Library does not work in bb repl

### ISSUE THREAD

**Issue by ieugen** [lispyclouds/bblgum#1]
Hi, 

I am working on a script that uses this library to ask for a user name.
I started a babashka repl in Calva and tried to execute the code bellow in a comment block.

I got the error: 
```
{:status 1, :result ("failed to run input: open /dev/tty: no such device or address")}
```

Working this the code bellow works, so I suspect there is an issue with interactive work.
BTW, I think the code bellow should be part of the documentation. 
```
export BABASHKA_CLASSPATH="$(clojure -Sdeps '{:deps {io.github.lispyclouds/bblgum {:git/sha "da049b2bf1bd7dad1c8296fd97c34e9401707719"}}}' -Spath)"

bb -e "(require '[bblgum.core :as b]) (b/gum {:cmd :input :opts {:placeholder \"User name:\"}})" 
```

**Comment by lispyclouds** [comment]
Yes, this would not work in some of the REPLs unless they have an command line interactive mode, which rules out most of the editor REPLs. I have been using the interactive parts of the code via a bb repl in the terminal with `rlwrap bb` or running the script. Can't really do much from the perspective of the lib unfortunately.

Thanks for the code snippet, will add it to the README!

**Comment by lispyclouds** [comment]
added the doc. lemme know if you know of a way to address the REPL issue, happy to support it! also feel free to close the issue too.

**Comment by ieugen** [comment]
I don't know how to handle that either. 
Maybe I will at some point .
In the meant time, maybe we should mention it in the README as a known issue. 
We can also ask on slack - will do that.
