### ISSUE TITLE
gum style doesn't seem to work

### ISSUE THREAD

**Issue by licht1stein** [lispyclouds/bblgum#2]
Thanks for the excellent lib! I have a problem -- everything seems to work, but `gum style`. This works fine in terminal: 

```sh
gum style foo
```

But this produces no output:

```clojure
(gum {:cmd :style :args ["foo"]})
```

**Comment by licht1stein** [comment]
Yes, but doesn't print. Also while scripting with your lib today I think I came up with a simpler API. I'll make a pr for you to take a look.

**Comment by lispyclouds** [comment]
> but doesn't print

Do you mean it doesn't style the output? Or there is not output? Could you be specific about `print`?

> I came up with a simpler API

Really looking forward to it!

**Comment by licht1stein** [comment]
Here it is, more or less: https://github.com/lispyclouds/bblgum/pull/3

**Comment by lispyclouds** [comment]
Thanks! Taking a look at it. But does the issue with no printing still exist?

**Comment by licht1stein** [comment]
Yes, nothing is printed

**Comment by lispyclouds** [comment]
Again, when you say printed, on the stdout of the script? If yes, that wont work as it is, you need to run `println` or something similar on the seq of the `:result`.

**Comment by lispyclouds** [comment]
Is this really an issue? Im not quite sure of it?

**Comment by licht1stein** [comment]
You need to update the git sha in the readme. 

And I'll demonstrate the issue in a min

**Comment by lispyclouds** [comment]
should be pointing to the butlast one now.

**Comment by licht1stein** [comment]
<img width="775" alt="image" src="https://user-images.githubusercontent.com/35418634/230212605-a8e88693-7bc6-4134-afdf-af86a43c865e.png">

Is this the expected behaviour? Cause it seems strange, that I can't use it as part of the flow.

**Comment by lispyclouds** [comment]
yes this is expected. the output of gum is on its stdout and is intercepted by bb and into the result map youre seeing. if gum wouldve printed on stderr it wouldve been the way youre expecting? this causes it: https://github.com/lispyclouds/bblgum/blob/main/src/bblgum/impl.clj#L23

**Comment by lispyclouds** [comment]
you can do something like `(run println result)` where `result` is the seq.

**Comment by licht1stein** [comment]
I wonder, how gum clears the output after, for example, printing a table or confirmation dialogue. Because I want disappearing prints :)

**Comment by licht1stein** [comment]
But I understand your answer, it seems there is no issue after all.

**Comment by lispyclouds** [comment]
> I wonder, how gum clears the output after, for example, printing a table or confirmation dialogue

Gum is doing it on `stderr` which we inherit, thats how it works. we can think of a way to inherit stdout too. it complicates the communication with gum a bit though as the answer comes there for others. any ideas welcome!

**Comment by lispyclouds** [comment]
Could you try passing :as :ignored and see if it produces the output you want?
