### ISSUE TITLE
Conflicting keys in bblgum opts and the command opts

### ISSUE THREAD

**Issue by lispyclouds** [lispyclouds/bblgum#4]
There could be a scenario when using the higher level API the keys to bblgum could collide with the ones that are intended as opts to the command being executed.

Example: if in the future one of gum's commands has an opt called `--in`, `--as`, `--gum-path` these would collide and they are interpreted as opts to bblgum as of now.

One possible solution could be to namespace them like `:bblgum/in`, `:bblgum/as` and `:bblgum/gum-path`. This could even simplify the opts merging process. Or use the lower level API. It could be a non-intuitive error if user run into the problem first.

cc @licht1stein

**Comment by licht1stein** [comment]
Wouldn't it be a premature optimization? It seems gum's api is already stabilized.

**Comment by lispyclouds** [comment]
Yeah I'm thinking in the future some command could take these options maybe. Let's reopen this when it's needed.
